BNE/BNE/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BNE.Util;
using BNE.Models;
using Serilog;
using Confluent.Kafka;
namespace BNE.Controllers
{
    public class PedidosController : Controller
    {
        private readonly IEmailSender _emailSender;
        IHttpContextAccessor HttpContextAccessor;
        public PedidosController(IHttpContextAccessor httpContextAccessor, IEmailSender emailSender)
        {
            HttpContextAccessor = httpContextAccessor;
            _emailSender = emailSender;
        }

        public async Task<IActionResult> IndexAsync(int? page)
        {
            DataServices dataService = new DataServices();
            string id_usuario_logado = @HttpContextAccessor.HttpContext.Session.GetString("IdNomeUsuarioLogado");
            Validacoes.TotalDadosPedidos = await dataService.PostTotalDadosPedidosAsync(id_usuario_logado,0);
            int Limite = Validacoes.TotalDadosPedidos.Count;
            if (page == null)
            {
                page = 1;
                Limite = 4;
            }
            else
            {
                Limite = Convert.ToInt32(page) * 4;
            }

            ViewBag.ListaProdutos = await dataService.PostDadosAsync(1);
            ViewBag.ListaTransacao = await dataService.PostDadosPedidosAsync(id_usuario_logado, Limite);
            ViewBag.ListaQuantidade = CapturaQuantidade();
            ViewBag.CurrentPage = page;
            ViewBag.TotalItems = Validacoes.TotalDadosPedidos.Count;
            Log.Information("Acesso a Produtos");
            return View();
        }

        public async Task<IActionResult> CriarPedidosAsync(PedidosModel formulario)
        {
            if (ModelState.IsValid)
            {
                string id_usuario_logado = @HttpContextAccessor.HttpContext.Session.GetString("IdNomeUsuarioLogado");
                string usuario_logado = @HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado");
                string email_usuario_logado= @HttpContextAccessor.HttpContext.Session.GetString("EmailUsuarioLogado");
                Validacoes.EmailEnviado = "NAO";
                int email = 0;
                var id = formulario.id;
                var id_produto = formulario.id_produto;
                var nome = formulario.nome_produto;
                var valor = formulario.valor;
                var quantidade = formulario.quantidade;
                DataServices dataService = new DataServices();
                string Mensagem = $"{usuario_logado} Seu pedido foi realizado " +
                                $" de {nome} quantidade {quantidade}";
                
                //ROTINA DE ENVIO de email  VIA C#
                await _emailSender.SendEmailAsync(email_usuario_logado, "REALIZAÇÃO DE PEDIDO", Mensagem);
                //ROTINA DE ENVIO VIA KAFKA
                //try
                //{
                //    SendMessageByKafka("Teste de Envio");
                //}
                //catch
                //{

                //}

                if (Validacoes.EmailEnviado == "SIM")
                    email = 1;
                ViewBag.ListaPedidos = await dataService.PostInsereDadosPedidosAsync(id, id_produto, int.Parse(id_usuario_logado), quantidade, email);
                Log.Information("Criando Pedidos Usuario "+ id_usuario_logado);
                return RedirectToAction("Index");
            }


            return View();
        }
        public async Task<IActionResult> AlterarPedidoAsync(int id)
        {
                DataServices dataService = new DataServices();
                string id_usuario_logado = @HttpContextAccessor.HttpContext.Session.GetString("IdNomeUsuarioLogado");
                string usuario_logado = @HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado");
                string email_usuario_logado = @HttpContextAccessor.HttpContext.Session.GetString("EmailUsuarioLogado");
                Validacoes.EmailEnviado = "NAO";
                var Pedido = await dataService.PostDadosEditPedidoAsync(id);
                ViewBag.IdPedido = Pedido.id;
                ViewBag.IdProduto = Pedido.id_produto;
                ViewBag.NomeProduto = Pedido.nome_produto;
                ViewBag.Quantidade = Pedido.quantidade;
                ViewBag.ListaProdutos = await dataService.PostDadosAsync(1);
                ViewBag.ListaQuantidade = CapturaQuantidade();
                Log.Information("Altera Pedidos Usuario " + id_usuario_logado);
                return View();
        }

        public async Task<IActionResult> AlterarRegistroPedidoAsync(PedidosModel formulario)
        {
            DataServices dataService = new DataServices();
            string id_usuario_logado = @HttpContextAccessor.HttpContext.Session.GetString("IdNomeUsuarioLogado");
            var Pedido = await dataService.PostAlteraDadosPedidosAsync(formulario.id, 
                                                                       formulario.id_produto, 
                                                                       int.Parse(id_usuario_logado),
                                                                       formulario.quantidade);

            Log.Information("Altera Pedidos Usuario " + id_usuario_logado);
            return RedirectToAction("Index");
        }


       
        [HttpGet]
        public async Task<IActionResult> ExcluirAsync(int Id)
        {
            DataServices dataService = new DataServices();
            string retorno = await dataService.PostExcluiDadosPedidosAsync(Id.ToString());
            Log.Information("Exclui Pedidos");
            return RedirectToAction("Index");

        }

        public List<string> CapturaQuantidade()
        {
            List<string> lista = new List<String>();
            for (int i = 1; i < 16; i++)
            {
                lista.Add(i.ToString());
            }
            return lista;
        }
        [HttpGet]
        public async Task<IActionResult> AtivarAsync(int Id)
        {
            DataServices dataService = new DataServices();
            string retorno = await dataService.PostAtivarDadosPedidosAsync(Id.ToString());
            Log.Information("Ativa Pedidos");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DesativarAsync(int Id)
        {
            DataServices dataService = new DataServices();
            string retorno = await dataService.PostDesativarDadosPedidosAsync(Id);
            Log.Information("Desativa Pedidos");
            return RedirectToAction("Index");
        }

        private string SendMessageByKafka(string message)
        {
            var config = new ProducerConfig { BootstrapServers = "localhost:9092" };

            using (var producer = new ProducerBuilder<Null, string>(config).Build())
            {
                try
                {
                    var sendResult = producer
                                        .ProduceAsync("fila_pedido", new Message<Null, string> { Value = message })
                                            .GetAwaiter()
                                                .GetResult();

                    return $"Mensagem '{sendResult.Value}' de '{sendResult.TopicPartitionOffset}'";
                }
                catch (ProduceException<Null, string> e)
                {
                    Console.WriteLine($"Delivery failed: {e.Error.Reason}");
                }
            }

            return string.Empty;
        }

    }

}

BNE/BNE/Views/Transacao/Dashboard.cshtml
@*<style>
    body {
        background-image: url('../../images/Bg.png')
    }
</style>*@
<style>
    body {
        background-color: #ffffff;
    }
</style>
<h3>Meu Dashboard</h3>
<br />
<br />

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>


<div id="canvas-holder" style="width:60%">
    <canvas id="chart-area"></canvas>
</div>

<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [@Html.Raw(ViewBag.Valores)],
                backgroundColor: [@Html.Raw(ViewBag.Cores)],
                label: 'Dataset 1'
            }],
            labels: [@Html.Raw(ViewBag.Labels)]
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };

</script>

BNE/BNE/Views/Transacao/ExcluirTransacao.cshtml
a@*<style>
    body {
        background-image: url('../../images/Bg.png')
    }
</style>*@
<style>
    body {
        background-color: #a03131;
    }
</style>

<div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:25px; padding:15px;width:400px;">

    <h3>Deseja Excluir a Transação Selecionada?</h3>
    <p><strong>Data:</strong> @ViewBag.Registro.Data.ToString()</p>
    <p><strong>Histórico:</strong> @ViewBag.Registro.Descricao.ToString()</p>
    <p><strong>Valor:</strong> @ViewBag.Registro.Valor.ToString("N")</p>


    @{
        var vId = 0;

        try
        {
            vId = int.Parse(ViewBag.Registro.Id.ToString());
        }
        catch { }
    }
    <div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:10px; padding:20px;width:350px;">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td style="width:50px"><button type="button" onclick="Cancelar()" class="btn btn-block btn-default">Cancelar</button></td>
                    <td style="width:50px"> <button type="button" onclick="Excluir(@vId)" class="btn btn-block btn-danger">Excluir</button></td>
                </tr>
            </tbody>
        </table>
    </div>


    @*<div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:25px; padding:15px;width:400px;">
        <button type="button" onclick="Cancelar()" class="btn btn-block btn-default">Cancelar</button>
        <button type="button" onclick="Excluir(@vId)" class="btn btn-block btn-danger">Excluir</button>
    </div>*@
</div>
    <script>
        function Excluir(id) {
            window.location.href = "../Excluir/" + id;

        }
        function Cancelar() {
            window.location.href = "../Index";
        }

    </script>

BNE/BNE/Views/Transacao/Index.cshtml
@model PedidosModel
@using PagedList;
@using PagedList.Core.Mvc;
@using cloudscribe.Web.Pagination
@using BNE.Util;

<link href="~/css/PagedList.css" rel="stylesheet" type="text/css" />
@*<style>
        body {
            background-image: url('../../images/Bg.png')
        }
    </style>*@
<style>
    body {
        background-color: #FFFFFF;
    }
</style>

<div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:25px; padding:15px;width:1000px;">

    <h2>Meus Pedidos</h2>
    <form asp-controller="Pedidos" asp-action="CriarPedidos">
        <table Border="2" align="center">
            <thead>
                <tr style="background-color: cadetblue">
                    <td width=450><label>Produtos</label></td>
                    <td width=250><label>Quantidade</label></td>
                </tr>
            </thead>

            <tbody>
                <tr>
                        
                    <td width=450>
                        <select asp-for="id" class="form-control">
                            @{
                                foreach (var item in (List<ProdutosModel>)ViewBag.ListaProdutos)
                                {
                                    <option value="@item.Id.ToString()">@item.Nome.ToString()</option>
                                }
                            }
                        </select>
                    </td>
                    <td width=220>
                        <select asp-for="quantidade" class="form-control">
                            @{

                                foreach (var item in (List<string>)ViewBag.ListaQuantidade)
                                {

                                    if (item.ToString() != "1")
                                    {
                                        <option value="@item.ToString()">@item.ToString()</option>
                                    }
                                    else
                                    {
                                        <option selected="selected" value="@item.ToString()">@item.ToString()</option>
                                    }
                                }

                            }
                        </select>
                    </td>
                 </tr>
            </tbody>
        </table>
        <div class="container"  style="background-color:rgba(239,239,239,0.95); border-radius:5px;width:500px">
    <table class="table table-bordered">
        <tbody>
            <tr height=5>
                @*<td top:50%><button type="button" class="btn btn-block btn-primary" onclick="RegistrarTransacao()">Registrar Transação</button></td>*@
                <td style="width:50px"><button type="submit" class="btn btn-block btn-success">     Registrar Pedido      </button></td>
                <td top:50%><button type="button" class="btn btn-block btn-primary" onclick="Voltar()">Voltar</button></td>
            </tr>
        </tbody>
    </table>
</div>
</form>
</div>
<br />

<br />
<div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:25px; padding:15px;width:1200px;">

    <form asp-controller="Pedidos" asp-action="Registrar">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>#</th>
                    <th>Codigo</th>
                    <th>Data</th>
                    <th>Produto</th>
                    <th>Quantidade</th>
                    <th>Valor</th>
                </tr>
            </thead>
            @{
                foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
                {
                    <tbody>
                    <tr>
                        <td><button type="button" class="btn btn-success" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                        <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                        <td>@item.Id.ToString()</td>
                        <td>@item.Data.ToString()</td>
                        <td >@item.Nome_Produto.ToString()</td>
                        <td align="right">@item.Quantidade.ToString("N")</td>
                        <td align="right">@item.Valor.ToString("C")</td>
                    </tr>
                    </tbody>
                }
            }
        </table>
        @*<div>
            <cs-pager cs-paging-pagesize="10"
                      cs-paging-pagenumber="@ViewBag.CurrentPage"
                      cs-paging-totalitems="@ViewBag.TotalItems"
                      cs-pagenumber-param="page"
                      cs-show-first-last="true"
                      cs-suppress-empty-nextprev="true"
                      cs-suppress-inactive-firstlast="true"
                      cs-first-page-text="Primeiro"
                      cs-last-page-text="Ultimo"
                      cs-pager-li-current-class="active"
                      cs-pager-li-non-active-class="disabled"
                      asp-controller="Transacao"
                      asp-action="Index">
            </cs-pager>

        </div>*@
    </form>
</div>


@*<button type="button" class="btn btn-block btn-primary" onclick="RegistrarTransacao()">Registrar Transação</button>*@
<script>

    function verData_I(valor) {
        var x = document.getElementById("DataSelI");
        var Ano = "";
        if (valor > 10) {
            alert("Formato data invalida!");
            if (valor = 11) {
                var stringAno = x.value;
                var stringMes = x.value;
                var stringDia = x.value;
                // var resultadoAno = stringExemplo.value.substring(0, 4);
                var resultadoAno = stringMes.substring(0, 4)
                var resultadoMes = stringMes.substring(6, 8)
                var resultadoDia = stringDia.substring(9, 11)
                var resultadoTotal = resultadoAno + "/" + resultadoMes + "/" + resultadoDia;
                x.value = resultadoAno + "-" + resultadoMes + "-" + resultadoDia;
            }

        }
            
    }
    function verData_F(valor) {
        var x = document.getElementById("DataSelF");
        var Ano = "";
        if (valor > 10) {
            alert("Formato data invalida!");
            if (valor = 11) {
                var stringAno = x.value;
                var stringMes = x.value;
                var stringDia = x.value;
                // var resultadoAno = stringExemplo.value.substring(0, 4);
                var resultadoAno = stringMes.substring(0, 4)
                var resultadoMes = stringMes.substring(6, 8)
                var resultadoDia = stringDia.substring(9, 11)
                var resultadoTotal = resultadoAno + "/" + resultadoMes + "/" + resultadoDia;
                x.value = resultadoAno + "-" + resultadoMes + "-" + resultadoDia;
            }

        }

    }


    function Voltar() {
        window.location.href = "../Home/Menu"
    }
    function Excluir(id) {
        window.location.href = "../Transacao/ExcluirTransacao/" + id;
    }
    function Editar(id) {
        window.location.href = "../Transacao/Registrar/" + id;
    }

</script>

BNE/BNE/Views/Transacao/TelaErro.cshtml
@*<style>
        body {
            background-image: url('../../images/Bg.png')
        }
    </style>*@
<style>
    body {
        background-color: #a03131;
    }
</style>

<div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:25px; padding:15px;width:400px;">

    <h2>Erro de Processamento</h2>
    <p><h4><strong>Contate o adminstrador de sistemas</strong></h4></p>
  

    <div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:10px; padding:20px;width:350px;">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td style="width:50px"><button type="button" onclick="Voltar()" class="btn btn-block btn-default">Voltar</button></td>
                </tr>
            </tbody>
        </table>
    </div>

</div>
<script>
        function Excluir(id) {
            window.location.href = "../Excluir/" + id;

        }
        function Voltar() {
            window.location.href = "../Transacao/Index";
        }

</script>