BNE/BNE/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BNE.Util;
using BNE.Models;
using Serilog;
using Serilog.Events;

namespace BNE.Controllers
{
    public class ProdutosController : Controller
    {
       
        private readonly IHttpContextAccessor HttpContextAccessor;
    
        public ProdutosController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
            ProdutosModel objProdutos = new ProdutosModel(HttpContextAccessor);
            Log.Information("Acesso a Produtos");
        }
        
        public async Task<IActionResult> IndexAsync()
        {
            DataServices dataService = new DataServices();
            ViewBag.ListaProdutos = await dataService.PostDadosAsync(0);
            Log.Information("Listando os Produtos");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CriarProdutosAsync(ProdutosModel formulario)
        {
            if(ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                var id=formulario.Id;
                var nome = formulario.Nome;
                var valor = formulario.Valor;
                DataServices dataService = new DataServices();
                ViewBag.ListaProdutos = await dataService.PostAlteraDadosAsync(id, nome, valor.ToString().Replace(",","."));
                Log.Information("Criando/Alterando Produtos usuario "+ @HttpContextAccessor.HttpContext.Session.GetString("IdNomeUsuarioLogado"));
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CriarProdutosAsync(int id)
        {
            if (id != 0)
            {
                DataServices dataService = new DataServices();
                ViewBag.Registro = await dataService.PostDadosEditAsync(id);
                ViewBag.Editar = "SIM";
            }
      
            return View();
        }



        [HttpGet]
        public IActionResult ExcluirProdutos(int? Id)
        {
            ProdutosModel objProdutos = new ProdutosModel(HttpContextAccessor);
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> ExcluirAsync(int Id)
        {
            DataServices dataService = new DataServices();
            string retorno = await dataService.PostExcluiDadosAsync(Id.ToString());
            Log.Information("Excluido Produtos usuario" + @HttpContextAccessor.HttpContext.Session.GetString("IdNomeUsuarioLogado"));
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> AtivarAsync(int Id)
        {
            DataServices dataService = new DataServices();
            string retorno = await dataService.PostAtivarDadosProdutosAsync(Id.ToString());
            Log.Information("Ativando Produtos usuario" + @HttpContextAccessor.HttpContext.Session.GetString("IdNomeUsuarioLogado"));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DesativarAsync(int Id)
        {
            DataServices dataService = new DataServices();
            string retorno = await dataService.PostDesativarDadosProdutosAsync(Id);
            Log.Information("Desativando Produtos usuario" + @HttpContextAccessor.HttpContext.Session.GetString("IdNomeUsuarioLogado"));
            return RedirectToAction("Index");
        }

    }
}

BNE/BNE/Views/Produtos/CriarProdutos.cshtml
@model ProdutosModel
@{
    ViewData["Title"] = "Criar Produtos";
}

<style>
    body {
        background-color: #ffffff;
    }
</style>
<div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:10px; padding:20px;width:600px;">

    <h3>Criar Produtos</h3>
    
    @{
        var vNome = "";
        var vValor = "";
        var vId = 0;

        try
        {
            vId = int.Parse(ViewBag.Registro.Id.ToString());
            vNome = ViewBag.Registro.Nome.ToString();
            vValor = ViewBag.Registro.Valor.ToString();
        }
        catch { }
    }

    <form asp-controller="Produtos" asp-action="CriarProdutos">
        <input type="hidden" asp-for="Id" value="@vId" />
        <div class="form-group">
            <label>Nome:</label>
            <input type="text" class="form-control" asp-for="Nome" value="@vNome" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Valor:</label>
            <input type="text" class="form-control" asp-for="Valor" value="@vValor" />
            <span asp-validation-for="Valor" class="text-danger"></span>
        </div>

        <div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:10px; padding:20px;width:500px;">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <td style="width:50px"><button type="submit" class="btn btn-block btn-success">Registrar</button></td>
                        @if (ViewBag.Editar == "SIM")
                        {
                            <td style="width:50px"><button type="button" class="btn btn-block btn-primary" onclick="VoltarEditar()">Voltar</button></td>
                        }
                        else
                        {
                            <td style="width:50px"><button type="button" class="btn btn-block btn-primary" onclick="Voltar()">Voltar</button></td>
                        }
                    </tr>
                </tbody>
            </table>
        </div>
    </form>
</div>
<script>
    function Voltar() {
        window.location.href = "../Produtos/Index"
    }
    function VoltarEditar() {
        window.location.href = "../Index"
    }
</script>

BNE/BNE/Views/Produtos/ExcluiProdutos.cshtml
@*<style>
    body {
        background-image: url('../../images/Bg.png')
    }
</style>*@
<style>
    body {
        background-color: #a03131;
    }
</style>
<div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:10px; padding:20px;width:600px;">

    <h3>Deseja Excluir o produto ?</h3>
    <p><strong>ID:</strong> @ViewBag.Registro.Id.ToString()</p>
    <p><strong>Data:</strong> @ViewBag.Registro.Data.ToString()</p>
    <p><strong>FormaPagto:</strong> @ViewBag.Registro.Descricao.ToString()</p>



    @{
        var vId = 0;

        try
        {
            vId = int.Parse(ViewBag.Registro.Id.ToString());
        }
        catch { }
    }
    <div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:10px; padding:20px;width:500px;">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td style="width:50px"><button type="button" onclick="Cancelar()" class="btn btn-block btn-info">Cancelar</button></td>
                    <td style="width:50px"><button type="button" onclick="Excluir(@vId)" class="btn btn-block btn-danger">Excluir</button></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
    <script>
        function Excluir(id) {
            window.location.href = "../Excluir/" + id;

        }
        function Cancelar() {
            window.location.href = "../Index";
        }

    </script>

BNE/BNE/Views/Produtos/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<style>
    body {
        background-color: #ffffff;
    }
</style>
<div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:10px; padding:20px;width:1000px;">

    <h3>Produtos</h3>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>#</th>
                <th>#</th>
                <th>Codigo</th>
                <th>Descrição</th>
                <th>Valor</th>
                <th>Ativo</th>

            </tr>
        </thead>
        @{
            foreach (var item in (List<ProdutosModel>)ViewBag.ListaProdutos)
            {
                <tbody>
                            <tr>
                                @{
                                    if (@item.Id != 0)
                                    {
                                        <td style="width:100px"><button type="button" class="btn btn-success" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                                        <td style="width:100px"><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                                        if (@item.Ativo == "SIM")
                                        {
                                            <td style="width:100px"><button type="button" class="btn btn-danger" onclick="Ativar(@item.Id.ToString())">Desativar</button></td>
                                        }
                                        else
                                        {
                                             <td style="width:100px"><button type="button" class="btn btn-danger" onclick="Desativar(@item.Id.ToString())">   Ativar   </button></td>
                                        }
                                        <td style="width:30px">@item.Id.ToString()</td>
                                        <td>@item.Nome.ToString()</td>
                                        <td>@item.Valor.ToString().Replace("R", "Receita / Entrada").Replace("D", "Despesa / Saída")</td>
                                        <td>@item.Ativo.ToString().Replace("R", "Receita / Entrada").Replace("D", "Despesa / Saída")</td>
                                    }
                                }
</tbody>
            }
        }
    </table>
    <div class="container" style="background-color:rgba(239,239,239,0.95); border-radius:10px; padding:20px;width:500px;">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td style="width:50px"><button type="button" class="btn btn-block btn-primary" onclick="CriarProdutos()">Criar Produtos</button></td>
                    <td style="width:50px"><button type="button" class="btn btn-block btn-primary" onclick="Voltar()">Voltar</button></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
    <script>
        function CriarProdutos() {
            window.location.href = "../Produtos/CriarProdutos"
        }
        function Excluir(id_conta) {
            window.location.href = "../Produtos/Excluir/" + id_conta;
        }
        function Ativar(id_conta) {
            window.location.href = "../Produtos/Desativar/" + id_conta;
        }
        function Desativar(id_conta) {
            window.location.href = "../Produtos/Ativar/" + id_conta;
        }
        function Editar(id_conta) {
            window.location.href = "../Produtos/CriarProdutos/" + id_conta;
        }
        function Voltar() {
            window.location.href = "../Home/Menu"
        }


    </script>